### PR TITLE
WIP: redesign of the search bar (CSS)

### PR DESCRIPTION
**Pull request by leovalais**
It currently look like this because the templates are not updated:

screenshot_2018-11-05 introduction 1

I propose to put it above the content to make it more visible, like so:

screenshot_2018-11-05 introduction

The extension `<<googlesearch>>` needs to be modified to have the "GO" button and a more
explicative `placeholder`.

**DO NOT MERGE UNTIL HTML_OF_WIKI CAN HANDLE CONDITIONAL TEMPLATES**

### CODE REVIEW

**Comment by leovalais** [comment]
Pull request of html_of_wiki: https://github.com/ocsigen/html_of_wiki/pull/79

**Comment by Drup** [comment]
Can't we put it in the menu bar instead, like in many website ? Just a search button, when you click, it expands in a text bar, and you can search.

**Comment by Drup** [comment]
(and this way, we can remove all these ridiculously large margins ....)

**Comment by leovalais** [comment]
screenshot_2018-11-06 introduction
screenshot_2018-11-06 introduction 1

**Comment by Drup** [comment]
Very nice, I like that version quite a lot more.

Does the website works on mobile? If so, makes sure your thing also does.

**Comment by leovalais** [comment]
With small resolutions, the bar is hidden. With higher widths (phone in landscape mode) the website does not work. I'll try to make it work at least in portrait mode.

**Pull request merged**
